# Generated by Django 3.2.12 on 2022-03-17 17:09

from django.db import migrations
from pathlib import Path
import json


def load_authors(apps, schema_editor):
    Author = apps.get_model("store", "Author")
    jsonfile = Path(__file__).parents[2] / "authors.json"

    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)
        for obj in objects:
            try:
                name = obj["name"]
                Author(name=name).save()
            except KeyError:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [migrations.RunPython(load_authors)]
