# Generated by Django 3.2.12 on 2022-03-17 17:47

from django.db import migrations
from pathlib import Path
import json


def load_books(apps, schema_editor):
    Book = apps.get_model("store", "Book")
    Author = apps.get_model("store", "Author")
    jsonfile = Path(__file__).parents[2] / "books.json"

    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)
        for obj in objects:
            try:
                title = obj["title"]
                author = obj["author"]
                Book(title=title, author=Author.objects.get(pk=author)).save()
            except KeyError:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_auto_20220317_1709"),
    ]

    operations = [migrations.RunPython(load_books)]
